/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.27.0
  Forc version: 0.32.2
  Fuel-Core version: 0.15.1
*/

import type {
  Interface,
  FunctionFragment,
  DecodedValue,
  Contract,
  BytesLike,
  BigNumberish,
  InvokeFunction,
  BN,
} from 'fuels';

export type AddressInput = { value: string };
export type AddressOutput = AddressInput;

interface ContractAbiInterface extends Interface {
  functions: {
    deposit: FunctionFragment;
    withdraw: FunctionFragment;
  };

  encodeFunctionData(functionFragment: 'deposit', values: [AddressInput]): Uint8Array;
  encodeFunctionData(functionFragment: 'withdraw', values: [AddressInput]): Uint8Array;

  decodeFunctionData(functionFragment: 'deposit', data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: 'withdraw', data: BytesLike): DecodedValue;
}

export class ContractAbi extends Contract {
  interface: ContractAbiInterface;
  functions: {
    deposit: InvokeFunction<[recipient: AddressInput], void>;
    withdraw: InvokeFunction<[recipient: AddressInput], void>;
  };
}
